import JSZip from 'jszip';
import { RobloxProject } from '../types/roblox';

export async function exportProjectAsZip(project: RobloxProject): Promise<Blob> {
  const zip = new JSZip();

  // 1. Create default.project.json for Rojo sync
  const rojoConfig = {
    name: project.name,
    tree: {
      $className: 'DataModel',
      ServerScriptService: {
        $className: 'ServerScriptService',
        Server: {
          $path: 'src/server',
        },
      },
      ReplicatedStorage: {
        $className: 'ReplicatedStorage',
        Shared: {
          $path: 'src/shared',
        },
      },
      StarterPlayer: {
        $className: 'StarterPlayer',
        StarterPlayerScripts: {
          $className: 'StarterPlayerScripts',
          Client: {
            $path: 'src/client',
          },
        },
      },
    },
  };

  zip.file('default.project.json', JSON.stringify(rojoConfig, null, 2));

  // 2. README with Studio guide
  const readmeContent = `# ${project.name}
Generated by BloxCraft AI Studio (Luau & Roblox Engine IDE)

## Quick Start in Roblox Studio
### Option A: Using Rojo (Recommended)
1. Install the Rojo CLI: \`cargo install rojo\` or download from https://rojo.space/
2. In your terminal, run:
   \`\`\`bash
   rojo serve
   \`\`\`
3. Open Roblox Studio, launch the Rojo Studio Plugin, and click **Connect**.

### Option B: Manual Copy-Paste
- Scripts in \`src/server/\` go to **game.ServerScriptService**
- Scripts in \`src/shared/\` go to **game.ReplicatedStorage**
- Scripts in \`src/client/\` go to **game.StarterPlayer.StarterPlayerScripts**

## Files included:
${project.files.map((f) => `- \`${f.folder || 'src'}/${f.name}\` (${f.type})`).join('\n')}
`;
  zip.file('README.md', readmeContent);

  // 3. Add all script files
  project.files.forEach((file) => {
    const folder = file.folder || 'src';
    const filePath = `${folder}/${file.name}`;
    zip.file(filePath, file.code);
  });

  return await zip.generateAsync({ type: 'blob' });
}
